
		import { initializeApp } from "https://www.gstatic.com/firebasejs/10.7.1/firebase-app.js";
		import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged, sendPasswordResetEmail, updatePassword, EmailAuthProvider, reauthenticateWithCredential, setPersistence, browserLocalPersistence } from "https://www.gstatic.com/firebasejs/10.7.1/firebase-auth.js";
		import { getDatabase, ref, set, push, onValue, update, remove, get } from "https://www.gstatic.com/firebasejs/10.7.1/firebase-database.js";

		const firebaseConfig = { apiKey: "AIzaSyCKcegYgu1v3zH6G3wNivJCt2-p23XrRuw", authDomain: "drive-1c329.firebaseapp.com", databaseURL: "https://drive-1c329-default-rtdb.firebaseio.com", projectId: "drive-1c329", storageBucket: "drive-1c329.appspot.com", messagingSenderId: "730477611624", appId: "1:730477611624:web:95f90d5753a7a28ebb89dd" };
		const app = initializeApp(firebaseConfig);
		const auth = getAuth(app);
		const db = getDatabase(app);

		setPersistence(auth, browserLocalPersistence).catch((error) => console.log("Persistence Error:", error));
		let folderPassword = null; let allGlobalFolders =[]; let pendingFolderNav = null; let curUser=null, myUID="", selFiles=new Set(), curFold='root', foldPath=[{id:'root',name:'Home'}]; let popupCb = null; let currentMediaList =[]; let currentMediaIndex = 0; let filesListenerAttached = false; let dbSnapshot = null; let movingFilesSet = new Set(); let isChatOpen = false; let html5QrcodeScanner = null; let allFilesCache =[];
		window.openPopup = (type, msg, status='info', cb=null) => { const p=document.getElementById('global-popup'), i=document.getElementById('pop-icon'), t=document.getElementById('pop-title'), m=document.getElementById('pop-msg'), o=document.getElementById('pop-ok'), c=document.getElementById('pop-cancel'); popupCb = cb; t.innerText = type==='confirm'?"Confirmation":(status==='success'?"Success":"Alert"); m.innerText = msg; i.className = `fas popup-icon ${status==='success'?'fa-check-circle pop-success':(status==='error'?'fa-times-circle pop-error':'fa-info-circle pop-info')}`; c.style.display=type==='confirm'?'inline-block':'none'; o.onclick=()=>{ p.style.display='none'; if(popupCb) popupCb(); }; c.onclick=()=>{ p.style.display='none'; }; p.style.display='flex'; };
		window.toggleAuth = (mode) => { document.getElementById('login-form').style.display = 'none'; document.getElementById('signup-form').style.display = 'none'; document.getElementById('forgot-form').style.display = 'none'; if (mode === 'login') document.getElementById('login-form').style.display = 'block'; else if (mode === 'signup') document.getElementById('signup-form').style.display = 'block'; else if (mode === 'forgot') document.getElementById('forgot-form').style.display = 'block'; };
		window.openModal = id => document.getElementById(id).style.display='flex';
		window.closeModal = id => document.getElementById(id).style.display='none';
		onAuthStateChanged(auth, u=>{ if(u){ curUser=u; init(); } else{ document.getElementById('auth-screen').style.display='flex'; document.getElementById('dashboard').style.display='none'; } });
		window.login = async () => { const email = document.getElementById('l-email').value, pass = document.getElementById('l-pass').value; try { await signInWithEmailAndPassword(auth, email, pass); } catch (e) { window.openPopup('alert', parseError(e.message), 'error'); } };
		window.sendMainPasswordReset = async () => { const email = document.getElementById('f-email-direct').value; if(!email) return window.openPopup('alert', 'Please enter your Gmail', 'error'); try { await sendPasswordResetEmail(auth, email); window.openPopup('success', 'Reset link sent to your Gmail!', 'success'); window.toggleAuth('login'); } catch(e) { window.openPopup('alert', parseError(e.message), 'error'); } };
		window.updateAvatarPreview = (name) => { const picInput = document.getElementById('r-pic'); const preview = document.getElementById('signup-pic-preview'); if(!picInput.files || picInput.files.length === 0) { preview.src = `https://ui-avatars.com/api/?name=${encodeURIComponent(name || 'User')}&background=cbd2d9&color=fff`; } };
		window.previewSignupPic = (input) => { if (input.files && input.files[0]) { const reader = new FileReader(); reader.onload = function(e) { document.getElementById('signup-pic-preview').src = e.target.result; }; reader.readAsDataURL(input.files[0]); } };
		window.signup = async () => { const name = document.getElementById('r-name').value; const email = document.getElementById('r-email').value; const pass = document.getElementById('r-pass').value; const picInput = document.getElementById('r-pic'); if (!name || !email || !pass) return window.openPopup('alert', 'Fill all fields', 'error'); const btn = document.getElementById('signup-btn'); if(btn) { btn.innerText = "Creating Account..."; btn.disabled = true; } let picUrl = `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=2d8cf0&color=fff`; if (picInput && picInput.files && picInput.files.length > 0) { try { if(btn) btn.innerText = "Uploading Picture..."; picUrl = await uploadToCloudinary(picInput.files[0]); } catch(e) { window.openPopup('alert', 'Image upload failed. Using default.', 'warning'); } } if(btn) btn.innerText = "Finalizing..."; createAcc(picUrl, name, email, pass); };
		async function uploadToCloudinary(file) { const fd = new FormData(); fd.append('file', file); fd.append('upload_preset', 'MiniDrive'); fd.append('folder', 'profiles'); const res = await fetch('https://api.cloudinary.com/v1_1/dhfbdy7rq/upload', { method: 'POST', body: fd }); const data = await res.json(); return data.secure_url; }
		async function createAcc(profilePic, name, email, pass) { try { const cred = await createUserWithEmailAndPassword(auth, email, pass); const uid = cred.user.uid; const customUID = `TD${Math.floor(Math.random() * 90000000 + 10000000)}${name.slice(0, 2).toUpperCase()}`; await set(ref(db, `users/${uid}`), { name, email, profilePic, customUID, storageLimitGB: 15, usedStorageBytes: 0 }); await set(ref(db, `uid_map/${customUID}`), uid); location.reload(); } catch (e) { window.openPopup('alert', parseError(e.message), 'error'); const btn = document.getElementById('signup-btn'); if(btn) { btn.innerText = "Create Account"; btn.disabled = false; } } }
		window.updateProfilePic = async (input) => { if (!input.files || input.files.length === 0) return; const status = document.getElementById('pic-upload-status'); if(status) { status.style.display = 'block'; status.innerText = "Uploading..."; status.style.color = "var(--success)"; } try { const url = await uploadToCloudinary(input.files[0]); await update(ref(db, `users/${curUser.uid}`), { profilePic: url }); const picEl = document.getElementById('my-profile-pic'); const headerPicEl = document.getElementById('header-profile-pic'); if(picEl) picEl.src = url; if(headerPicEl) headerPicEl.src = url; if(status) status.innerText = "Updated successfully!"; setTimeout(() => { if(status) status.style.display = 'none'; }, 3000); } catch(e) { if(status) { status.innerText = "Upload failed!"; status.style.color = "var(--danger)"; } setTimeout(() => { if(status) { status.style.display = 'none'; status.style.color = "var(--success)"; } }, 3000); } input.value = ""; };
		window.copyUID = () => { if(!myUID) return; navigator.clipboard.writeText(myUID).then(() => { window.openPopup('success', 'UID Copied to Clipboard!', 'success'); }); };
		window.showMyQR = () => { if(!myUID) return; document.getElementById('my-qr-img').src = `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${myUID}`; document.getElementById('qr-uid-text').innerText = myUID; window.openModal('qr-modal'); };
		window.openScanner = () => { window.openModal('scanner-modal'); html5QrcodeScanner = new Html5QrcodeScanner("reader", { fps: 10, qrbox: {width: 250, height: 250} }, false); html5QrcodeScanner.render((decodedText) => { document.getElementById('share-uid').value = decodedText; window.closeScanner(); }, (error) => { /* ignore */ }); };
		window.closeScanner = () => { if (html5QrcodeScanner) { html5QrcodeScanner.clear().catch(err => console.log("Failed to clear scanner", err)); html5QrcodeScanner = null; } window.closeModal('scanner-modal'); };
		function updateProfileUI(u) { if (!u.customUID) return; myUID = u.customUID; const inboxUidEl = document.getElementById('my-uid-inbox'); if(inboxUidEl) inboxUidEl.innerText = myUID; const limit = u.storageLimitGB ?? 15; const usedGB = (u.usedStorageBytes ?? 0) / (1024 ** 3); document.getElementById('store-txt').innerText = `${usedGB.toFixed(2)} / ${limit} GB`; document.getElementById('store-bar').style.width = Math.min((usedGB / limit) * 100, 100) + "%"; folderPassword = u.folderPassword || null; const finalPicUrl = u.profilePic || u.faceUrl || `https://ui-avatars.com/api/?name=${encodeURIComponent(u.name)}&background=2d8cf0&color=fff`; const headerPicEl = document.getElementById('header-profile-pic'); const headerNameEl = document.getElementById('header-profile-name'); if(headerPicEl) headerPicEl.src = finalPicUrl; if(headerNameEl) headerNameEl.innerText = u.name; const picEl = document.getElementById('my-profile-pic'); const nameEl = document.getElementById('my-profile-name'); const emailEl = document.getElementById('my-profile-email'); if(picEl) picEl.src = finalPicUrl; if(nameEl) nameEl.innerText = u.name; if(emailEl) emailEl.innerText = u.email; }
		function init() { document.getElementById('auth-screen').style.display = 'none'; document.getElementById('dashboard').style.display = 'flex'; const cachedUser = localStorage.getItem('md_user_cache'); if(cachedUser) { updateProfileUI(JSON.parse(cachedUser)); } onValue(ref(db, `users/${curUser.uid}`), async (snapshot) => { if (!snapshot.exists()) return; const u = snapshot.val(); localStorage.setItem('md_user_cache', JSON.stringify(u)); updateProfileUI(u); }); loadFiles(); listenToChat(); listenNotifs(); }
		function loadFiles() { if(filesListenerAttached) return; filesListenerAttached = true; const cachedFiles = localStorage.getItem('md_files_cache'); if(cachedFiles) { allFilesCache = JSON.parse(cachedFiles); renderFilesArray(allFilesCache); } onValue(ref(db,`users/${curUser.uid}/files`), snapshot=>{ dbSnapshot = snapshot; allFilesCache =[]; if(snapshot.exists()) { snapshot.forEach(c => { allFilesCache.push({ k:c.key, ...c.val() }); }); } localStorage.setItem('md_files_cache', JSON.stringify(allFilesCache)); renderFilesArray(allFilesCache); }); }
		function renderFilesArray(allFiles) { const g = document.getElementById('file-grid'); g.innerHTML = ""; allGlobalFolders = allFiles.filter(f => f.type === 'folder'); const visibleFiles = allFiles.filter(f => (f.parentId ?? 'root') === curFold); visibleFiles.sort((a,b)=>{ if(a.type==='folder' && b.type!=='folder') return -1; if(a.type!=='folder' && b.type==='folder') return 1; return (b.createdAt||0)-(a.createdAt||0); }); currentMediaList = visibleFiles.filter(f => f.type==='image' || f.type==='video'); visibleFiles.forEach(f=>{ const el = document.createElement('div'); el.className = "file-card"; let thumb = ""; let lockBadge = f.isLocked ? `<i class="fas fa-lock lock-badge"></i>` : ""; if(f.type === 'folder'){ thumb = `<i class="fas fa-folder file-icon" style="color:#f7b731"></i> ${lockBadge}`; } else if(f.type === 'image'){ thumb = `<img src="${f.url}" class="file-thumb">`; } else if(f.type === 'video'){ thumb = `<img src="${f.url.replace('/video/upload/', '/video/upload/so_1/').replace('.mp4', '.jpg')}" class="file-thumb"><div class="type-badge">VIDEO</div>`; } else{ thumb = `<i class="fas fa-file file-icon"></i>`; } el.innerHTML = `<div class="thumb-wrapper">${thumb}</div><span class="file-name">${f.name}</span>`; let pressTimer = null; let longPressed = false; let isScrolling = false; let startX = 0, startY = 0; el.addEventListener("touchstart", (e) => { longPressed = false; isScrolling = false; startX = e.touches[0].clientX; startY = e.touches[0].clientY; pressTimer = setTimeout(() => { if(!isScrolling && !movingFilesSet.size) { longPressed = true; togSel(f.k, el); navigator.vibrate?.(40); } }, 500); }); el.addEventListener("touchmove", (e) => { let moveX = Math.abs(e.touches[0].clientX - startX); let moveY = Math.abs(e.touches[0].clientY - startY); if (moveX > 10 || moveY > 10) { isScrolling = true; clearTimeout(pressTimer); } }); el.addEventListener("touchend", () => { clearTimeout(pressTimer); if(longPressed || isScrolling) return; if(selFiles.size > 0){ togSel(f.k, el); return; } if (f.type === 'folder') window.attemptNav(f.k, f.name, f.isLocked); else if (f.type === 'image') { window.cacheFile(f.url); viewPhoto(f.url, f.k); } else if (f.type === 'video') { window.cacheFile(f.url); playVideoInApp(f.url, f.k); } else { window.cacheFile(f.url); window.open(f.url); } }); g.appendChild(el); }); }
		window.cacheFile = async (url) => { if(!url) return; try { const cache = await caches.open('minidrive-media'); const match = await cache.match(url); if(!match) { const res = await fetch(url); if(res.ok) await cache.put(url, res); } } catch(e) { console.log('Cache error', e); } };
		window.syncAllOffline = async () => { window.openPopup('info', 'Downloading all files for offline use. Please wait...', 'info'); window.closeModal('settings-modal'); try { const cache = await caches.open('minidrive-media'); let count = 0; for(let f of allFilesCache) { if(f.url && f.type !== 'folder') { const match = await cache.match(f.url); if(!match) { const res = await fetch(f.url); if(res.ok) { await cache.put(f.url, res); count++; } } } } window.openPopup('success', `Offline Sync Complete! Saved ${count} new items.`, 'success'); } catch(e) { window.openPopup('error', 'Sync failed. Check connection.', 'error'); } };
		window.uploadFilesXHR = async (input) => { const files = Array.from(input.files); if (!files || files.length === 0) return; window.openPopup('info', `Uploading ${files.length} files...`, 'info'); const grid = document.getElementById('file-grid'); for (let i = 0; i < files.length; i++) { const file = files[i]; const tempId = `up-${Date.now()}-${i}`; const tempCard = document.createElement('div'); tempCard.className = "file-card"; tempCard.id = tempId; tempCard.innerHTML = `<div class="thumb-wrapper" style="background:#57606f; color:white;"><small id="p-${tempId}" style="font-weight:bold;">0%</small></div><span class="file-name">${file.name}</span>`; grid.prepend(tempCard); try { let uploadedUrl = await uploadNormal(file, tempId); let type = 'file'; if(file.type.startsWith('image')) type='image'; else if(file.type.startsWith('video')) type='video'; await set(ref(db, `users/${curUser.uid}/files/f_${Date.now()}_${Math.random().toString(36).substr(2,5)}`), { name: file.name, url: uploadedUrl, type: type, size: file.size, parentId: curFold, createdAt: Date.now() }); const uRef = ref(db, `users/${curUser.uid}`); const s = await get(uRef); if(s.exists()) update(uRef, { usedStorageBytes: (s.val().usedStorageBytes||0) + file.size }); document.getElementById(tempId).remove(); } catch (e) { document.getElementById(`p-${tempId}`).innerText = "Failed"; } } input.value = ""; };
		function uploadNormal(file, tempId) { return new Promise((resolve, reject) => { const xhr = new XMLHttpRequest(); const fd = new FormData(); fd.append("file", file); fd.append("upload_preset", "MiniDrive"); fd.append("resource_type", "auto"); xhr.open("POST", `https://api.cloudinary.com/v1_1/dhfbdy7rq/upload`, true); xhr.timeout = 0; xhr.upload.onprogress = (e) => { if (e.lengthComputable) { const pEl = document.getElementById(`p-${tempId}`); if(pEl) pEl.innerText = Math.round((e.loaded / e.total) * 100) + "%"; } }; xhr.onload = () => { if (xhr.status >= 200 && xhr.status < 300) resolve(JSON.parse(xhr.responseText).secure_url); else reject(); }; xhr.onerror = () => reject(); xhr.send(fd); }); }
		function listenNotifs() { onValue(ref(db, `users/${curUser.uid}/notifications`), snap => { const dot = document.getElementById('notif-dot'); if(snap.exists()) { dot.style.display = 'flex'; dot.innerText = snap.size; } else { dot.style.display = 'none'; } }); }
		window.shareFiles = async () => { const rUid = document.getElementById('share-uid').value.trim(); if(!rUid) return window.openPopup('alert', 'Please enter Receiver UID', 'error'); try { const snap = await get(ref(db, `uid_map/${rUid}`)); if(!snap.exists()) return window.openPopup('alert', 'User not found! Check UID.', 'error'); const realUid = snap.val(); if(realUid === curUser.uid) return window.openPopup('alert', 'You cannot share files to yourself!', 'error'); let filesToShare =[]; for(let k of selFiles) { const fSnap = await get(ref(db, `users/${curUser.uid}/files/${k}`)); if(fSnap.exists()) filesToShare.push(fSnap.val()); } const myUserSnap = await get(ref(db, `users/${curUser.uid}`)); const myData = myUserSnap.val(); const myPic = myData.profilePic || myData.faceUrl || `https://ui-avatars.com/api/?name=${encodeURIComponent(myData.name)}&background=2d8cf0&color=fff`; await push(ref(db, `users/${realUid}/notifications`), { senderName: myData.name, senderUid: myUID, senderPic: myPic, items: filesToShare, time: Date.now() }); window.closeModal('share-modal'); window.openPopup('success', 'Files sent successfully!', 'success'); selFiles.clear(); document.getElementById('sel-actions').style.display = 'none'; renderFilesArray(allFilesCache); document.getElementById('share-uid').value = ''; } catch(e) { window.openPopup('alert', 'Sharing failed.', 'error'); } };
		window.loadNotifs = async () => { const list = document.getElementById('notif-list'); list.innerHTML = '<p style="text-align:center;font-size:12px;">Loading...</p>'; const snap = await get(ref(db, `users/${curUser.uid}/notifications`)); if(!snap.exists()) { list.innerHTML = '<p style="text-align:center;font-size:12px;color:#777;">Inbox is empty.</p>'; return; } list.innerHTML = ''; let folderOpts = `<option value="root">/ Home</option>`; allGlobalFolders.forEach(f => { folderOpts += `<option value="${f.k}">📁 ${f.name}</option>`; }); snap.forEach(child => { const n = child.val(); const dateStr = new Date(n.time).toLocaleString(); const senderPic = n.senderPic || `https://ui-avatars.com/api/?name=${encodeURIComponent(n.senderName)}&background=2d8cf0&color=fff`; list.innerHTML += `<div style="background:var(--bg); padding:15px; border-radius:15px; box-shadow:inset 3px 3px 6px #a3b1c6, inset -3px -3px 6px #ffffff; font-size:13px; color:var(--text);"><div style="display:flex; align-items:center; gap:10px; margin-bottom:12px; padding-bottom:10px; border-bottom:1px solid #cbd2d9;"><img src="${senderPic}" style="width:35px; height:35px; border-radius:50%; object-fit:cover; border:2px solid var(--accent);"><div><div style="font-weight:bold; color:var(--accent); font-size:13px;">${n.senderName}</div><div style="font-size:10px; color:#777;">UID: ${n.senderUid || 'Unknown'}</div></div></div><div style="margin-bottom:8px;"><b>Files attached:</b> ${n.items.length} items</div><div style="margin-bottom:8px; font-size:10px; color:#888;">${dateStr}</div><p style="font-size:11px; font-weight:bold; margin-top:10px;">Select folder to save:</p><select id="sel-fold-${child.key}" class="neu-inset neu-input" style="padding:10px; margin-top:5px; margin-bottom:15px; font-size:12px; width:100%;">${folderOpts}</select><div style="display:flex; gap:10px;"><button class="neu-btn" style="flex:1; padding:10px; font-size:12px;" onclick="window.acceptShare('${child.key}')">Save</button><button class="neu-btn" style="flex:1; padding:10px; font-size:12px; color:var(--danger);" onclick="window.deleteNotif('${child.key}')">Delete</button></div></div>`; }); };
		window.acceptShare = async (notifId) => { const targetFolder = document.getElementById(`sel-fold-${notifId}`).value; try { const nSnap = await get(ref(db, `users/${curUser.uid}/notifications/${notifId}`)); if(!nSnap.exists()) return; const items = nSnap.val().items; let totalSize = 0; for(let item of items) { const newItem = {...item, parentId: targetFolder, createdAt: Date.now()}; delete newItem.k; await set(ref(db, `users/${curUser.uid}/files/f_${Date.now()}_${Math.random().toString(36).substr(2,5)}`), newItem); if(item.size) totalSize += item.size; } const uRef = ref(db, `users/${curUser.uid}`); const uSnap = await get(uRef); if(uSnap.exists()) { await update(uRef, { usedStorageBytes: (uSnap.val().usedStorageBytes||0) + totalSize }); } await remove(ref(db, `users/${curUser.uid}/notifications/${notifId}`)); window.loadNotifs(); window.openPopup('success', 'Files saved to folder successfully!', 'success'); } catch(e) { window.openPopup('alert', 'Error saving files.', 'error'); } };
		window.deleteNotif = async (notifId) => { await remove(ref(db, `users/${curUser.uid}/notifications/${notifId}`)); window.loadNotifs(); };
		function listenToChat() { onValue(ref(db, `users/${curUser.uid}/chat`), snap => { const msgsBox = document.getElementById('chat-msgs'); msgsBox.innerHTML = ''; let unread = 0; snap.forEach(child => { const msg = child.val(); const div = document.createElement('div'); div.className = `msg ${msg.sender === 'user' ? 'msg-me' : 'msg-admin'}`; div.innerText = msg.text; msgsBox.appendChild(div); if (msg.sender === 'admin' && !msg.read) unread++; }); msgsBox.scrollTop = msgsBox.scrollHeight; const badge = document.getElementById('chat-badge'); if (!isChatOpen && unread > 0) { badge.style.display = 'flex'; badge.innerText = unread; } else { badge.style.display = 'none'; } }); }
		window.openChat = () => { isChatOpen = true; document.getElementById('chat-badge').style.display = 'none'; window.openModal('chat-modal'); get(ref(db, `users/${curUser.uid}/chat`)).then(snap => { const updates = {}; snap.forEach(c => { if (c.val().sender === 'admin' && !c.val().read) { updates[`users/${curUser.uid}/chat/${c.key}/read`] = true; } }); if (Object.keys(updates).length > 0) update(ref(db), updates); }); };
		window.closeChat = () => { isChatOpen = false; window.closeModal('chat-modal'); };
		window.sendChat = async () => { const input = document.getElementById('chat-in'); const text = input.value.trim(); if(!text) return; input.value = ''; await push(ref(db, `users/${curUser.uid}/chat`), { sender: 'user', text: text, time: Date.now() }); };
		window.startMoveMode = () => { if (selFiles.size === 0) return; movingFilesSet = new Set(selFiles); selFiles.clear(); document.getElementById('sel-actions').style.display = 'none'; document.getElementById('main-fabs').style.display = 'none'; document.getElementById('move-action-bar').style.display = 'flex'; document.getElementById('move-txt').innerText = `Moving ${movingFilesSet.size} items`; window.nav('root', 'Home'); };
		window.confirmMoveHere = async () => { if (movingFilesSet.has(curFold)) return window.openPopup('alert', 'Cannot move a folder inside itself!', 'error'); try { const updates = {}; movingFilesSet.forEach(fileId => { updates[`users/${curUser.uid}/files/${fileId}/parentId`] = curFold; }); await update(ref(db), updates); window.openPopup('success', 'Files moved!', 'success'); } catch (e) { window.openPopup('alert', 'Move failed!', 'error'); } window.cancelMove(); };
		window.cancelMove = () => { movingFilesSet.clear(); document.getElementById('move-action-bar').style.display = 'none'; document.getElementById('main-fabs').style.display = 'flex'; renderFilesArray(allFilesCache); };
		window.openSettings = () => { window.openModal('settings-modal'); window.showSettingsView('main'); };
		window.showSettingsView = (viewName) => { document.getElementById('settings-main-view').style.display = 'none'; document.getElementById('settings-lock-view').style.display = 'none'; document.getElementById('settings-password-view').style.display = 'none'; document.getElementById('settings-admin-view').style.display = 'none'; const profileView = document.getElementById('settings-profile-view'); if(profileView) profileView.style.display = 'none'; if (viewName === 'main') { document.getElementById('settings-main-view').style.display = 'block'; } else if (viewName === 'lock') { document.getElementById('settings-lock-view').style.display = 'block'; document.getElementById('new-lock-pass').value = ''; document.getElementById('conf-lock-pass').value = ''; document.getElementById('verify-lock-pass').value = ''; document.getElementById('change-lock-pass').value = ''; if (!folderPassword) { document.getElementById('lock-setup-view').style.display = 'block'; document.getElementById('lock-verify-view').style.display = 'none'; document.getElementById('lock-manage-view').style.display = 'none'; } else { document.getElementById('lock-setup-view').style.display = 'none'; document.getElementById('lock-verify-view').style.display = 'block'; document.getElementById('lock-manage-view').style.display = 'none'; } } else if (viewName === 'password') { document.getElementById('settings-password-view').style.display = 'block'; document.getElementById('old-login-pass').value = ''; document.getElementById('new-login-pass').value = ''; document.getElementById('conf-login-pass').value = ''; } else if (viewName === 'admin') { document.getElementById('settings-admin-view').style.display = 'block'; } else if (viewName === 'profile') { if(profileView) profileView.style.display = 'block'; } };
		window.setupNewLock = async () => { const p1 = document.getElementById('new-lock-pass').value, p2 = document.getElementById('conf-lock-pass').value; if(!p1 || p1 !== p2) return window.openPopup('alert', 'Passwords do not match!', 'error'); await update(ref(db, `users/${curUser.uid}`), { folderPassword: p1 }); folderPassword = p1; window.openPopup('success', 'Lock Setup Successful!', 'success'); window.showSettingsView('lock'); };
		window.verifyLockSettings = () => { const p = document.getElementById('verify-lock-pass').value; if(p === folderPassword) { document.getElementById('lock-verify-view').style.display = 'none'; document.getElementById('lock-manage-view').style.display = 'block'; window.loadLockFolderList(); } else window.openPopup('alert', 'Wrong Password!', 'error'); };
		window.loadLockFolderList = () => { const list = document.getElementById('lock-folder-list'); list.innerHTML = ''; if(allGlobalFolders.length === 0) return list.innerHTML = "No folders found."; allGlobalFolders.forEach(f => { list.innerHTML += `<div class="lock-folder-item"><input type="checkbox" id="chk-${f.k}" ${f.isLocked ? 'checked' : ''}> <label for="chk-${f.k}" style="font-weight:bold; width:100%;"><i class="fas fa-folder" style="color:#f7b731; margin-right:5px;"></i> ${f.name}</label></div>`; }); };
		window.saveFolderLockChanges = async () => { const updates = {}; allGlobalFolders.forEach(f => { updates[`users/${curUser.uid}/files/${f.k}/isLocked`] = document.getElementById(`chk-${f.k}`).checked; }); await update(ref(db), updates); window.openPopup('success', 'Folder Locks Saved!', 'success'); };
		window.changeFolderLock = async () => { const newPass = document.getElementById('change-lock-pass').value; if(!newPass) return window.openPopup('alert', 'Enter new password', 'error'); await update(ref(db, `users/${curUser.uid}`), { folderPassword: newPass }); folderPassword = newPass; window.openPopup('success', 'Password Changed!', 'success'); document.getElementById('change-lock-pass').value = ''; };
		window.forgotFolderLock = () => { window.openPopup('confirm', 'Reset Folder Password? A link will be sent to your Gmail. Your folder locks will be removed.', 'warning', async () => { try { await sendPasswordResetEmail(auth, curUser.email); await update(ref(db, `users/${curUser.uid}`), { folderPassword: null }); folderPassword = null; const updates = {}; allGlobalFolders.forEach(f => { updates[`users/${curUser.uid}/files/${f.k}/isLocked`] = false; }); if(Object.keys(updates).length > 0) await update(ref(db), updates); window.openPopup('success', 'Reset link sent! Locks cleared.', 'success'); window.showSettingsView('main'); } catch(e) { window.openPopup('alert', 'Failed to send email.', 'error'); } }); };
		window.updateLoginPass = async () => { const oldPass = document.getElementById('old-login-pass').value; const newPass = document.getElementById('new-login-pass').value; const confPass = document.getElementById('conf-login-pass').value; if (!oldPass || !newPass || !confPass) return window.openPopup('alert', 'Please fill all fields.', 'error'); if (newPass !== confPass) return window.openPopup('alert', 'New passwords do not match!', 'error'); if (newPass.length < 6) return window.openPopup('alert', 'Password must be at least 6 characters.', 'error'); try { const credential = EmailAuthProvider.credential(curUser.email, oldPass); await reauthenticateWithCredential(curUser, credential); await updatePassword(curUser, newPass); window.openPopup('success', 'Login Password updated successfully!', 'success'); window.showSettingsView('main'); } catch(e) { if(e.code === 'auth/invalid-credential' || e.code === 'auth/wrong-password') { window.openPopup('alert', 'Current password is incorrect!', 'error'); } else { window.openPopup('alert', parseError(e.message), 'error'); } } };
		window.openAdminInfo = async () => { window.showSettingsView('admin'); const snap = await get(ref(db, 'admin_settings/admin_info')); if (snap.exists()) { const data = snap.val(); document.getElementById('admin-pic').src = data.profilePic || 'https://via.placeholder.com/80'; document.getElementById('admin-name').innerText = data.name || 'Admin'; document.getElementById('admin-address').innerText = data.address || 'No address provided'; const linksDiv = document.getElementById('admin-links'); linksDiv.innerHTML = ''; if (data.links) { Object.values(data.links).forEach(l => { linksDiv.innerHTML += `<button class="neu-btn" style="font-size:12px; padding:10px;" onclick="window.open('${l.url}', '_blank')"><i class="fas fa-link" style="margin-right:8px;"></i> ${l.title}</button>`; }); } } else { document.getElementById('admin-name').innerText = 'Admin info not uploaded yet.'; document.getElementById('admin-address').innerText = ''; document.getElementById('admin-links').innerHTML = ''; } };
		window.logout = () => { window.openPopup('confirm', 'Are you sure you want to log out?', 'warning', () => { signOut(auth).then(() => location.reload()); }); };
		window.attemptNav = (id, name, isLocked) => { if (isLocked) { pendingFolderNav = { id, name }; document.getElementById('open-folder-pass').value = ""; window.openModal('verify-pass-modal'); } else { window.nav(id, name); } };
		window.verifyAndOpenFolder = () => { const pass = document.getElementById('open-folder-pass').value; if(pass === folderPassword) { window.closeModal('verify-pass-modal'); window.nav(pendingFolderNav.id, pendingFolderNav.name); pendingFolderNav = null; } else { window.openPopup('alert', 'Wrong Password!', 'error'); } };
		window.createFolder = () => { const n = document.getElementById('new-fold-name').value; if(n){ push(ref(db,`users/${curUser.uid}/files`),{name:n,type:'folder',parentId:curFold,createdAt:Date.now()}); document.getElementById('new-fold-name').value=""; window.closeModal('folder-modal'); } };
		window.deleteSelected = async () => { let t = 0; for (const k of selFiles) { const fRef = ref(db, `users/${curUser.uid}/files/${k}`); const snap = await get(fRef); if (snap.exists()) { const f = snap.val(); if(f.size) t += f.size; await remove(fRef); } } const us = await get(ref(db, `users/${curUser.uid}/usedStorageBytes`)); let c = us.val() || 0; await update(ref(db, `users/${curUser.uid}`), { usedStorageBytes: Math.max(c - t, 0) }); selFiles.clear(); document.getElementById('sel-actions').style.display='none'; document.getElementById('global-popup').style.display='none'; };
		function findMediaIndex(key) { return currentMediaList.findIndex(m => m.k === key); }
		window.nextMedia = () => { if(currentMediaList.length === 0) return; currentMediaIndex = (currentMediaIndex + 1) % currentMediaList.length; openMediaByIndex(currentMediaIndex); };
		window.prevMedia = () => { if(currentMediaList.length === 0) return; currentMediaIndex = (currentMediaIndex - 1 + currentMediaList.length) % currentMediaList.length; openMediaByIndex(currentMediaIndex); };
		function openMediaByIndex(idx) { const item = currentMediaList[idx]; if(item.type === 'video') { window.closePhotoViewer(); window.playVideoInApp(item.url, item.k, false); } else if (item.type === 'image') { window.closeVideoPlayer(); window.viewPhoto(item.url, item.k, false); } }
		window.viewPhoto = (url, key, resetIndex=true) => { if(resetIndex) currentMediaIndex = findMediaIndex(key); document.getElementById('main-photo').src = url; document.getElementById('photo-viewer').style.display = 'flex'; };
		window.closePhotoViewer = () => { document.getElementById('photo-viewer').style.display = 'none'; document.getElementById('main-photo').src = ""; };
		window.playVideoInApp = (url, key, resetIndex=true) => { if(resetIndex) currentMediaIndex = findMediaIndex(key); const p=document.getElementById('custom-player'), v=document.getElementById('main-video'), s=document.getElementById('vid-seek'); v.src = url; p.style.display = 'flex'; v.play(); document.getElementById('play-btn').innerHTML = '<i class="fas fa-pause"></i>'; v.ontimeupdate=()=>{ s.value=(v.currentTime/v.duration)*100; let m=Math.floor(v.currentTime/60), sec=Math.floor(v.currentTime%60); document.getElementById('vid-time-txt').innerText=`${m}:${sec<10?'0':''}${sec}`; }; s.oninput=()=>{ v.currentTime=(s.value/100)*v.duration; }; };
		window.toggleVideo = () => { const v=document.getElementById('main-video'), b=document.getElementById('play-btn'); if(v.paused){ v.play(); b.innerHTML='<i class="fas fa-pause"></i>'; } else { v.pause(); b.innerHTML='<i class="fas fa-play"></i>'; } };
		window.closeVideoPlayer = () => { document.getElementById('custom-player').style.display='none'; document.getElementById('main-video').pause(); document.getElementById('main-video').src=""; };
		function togSel(k,el) { if(selFiles.has(k)){selFiles.delete(k);el.classList.remove('selected');}else{selFiles.add(k);el.classList.add('selected');} document.getElementById('sel-actions').style.display=selFiles.size>0?'flex':'none'; }
		window.nav = (id, name) => { curFold = id; foldPath.push({ id, name }); upPath(); history.pushState({}, ""); renderFilesArray(allFilesCache); };
		window.goBack = () => { if(curFold === 'root') return; foldPath.pop(); curFold = foldPath[foldPath.length - 1].id; upPath(); renderFilesArray(allFilesCache); };
		function upPath() { document.getElementById('path-bar').style.display=curFold==='root'?'none':'flex'; document.getElementById('curr-folder').innerText="/ "+foldPath.map(p=>p.name).join(" / "); }
		function parseError(msg) { if (msg.includes("user-not-found")) return "User not found"; if (msg.includes("wrong-password")) return "Wrong password"; if (msg.includes("email-already-in-use")) return "Email already registered"; return msg; }
